# nixpacks.toml

# Use the Makefile to build the application
[phases.build]
cmd = "go build -v -o ./bin/sber-scrape ./cmd/sber-scrape"

# Use the Makefile to start the application
[phases.start]
cmd = "./bin/sber-scrape"

